name: Build OptCuts

on:
  push

jobs:
  build:
    name: Build OptCuts - Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: recursive

      - name: Update packages
        run: sudo apt-get update
      - name: Install packages
        run: sudo apt-get install --fix-missing libgl1-mesa-dev xorg-dev libglu1-mesa-dev

      - name: Run CMake
        run: |
            mkdir build
            cd build
            cmake -DCMAKE_BUILD_TYPE=Release ..
      
      - name: Build
        run: |
            cd build
            make -j 12

      # Upload the build results - Retained for 90 days by default
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: Build Products
          path: build/OptCuts_bin

      - name: Run Tests
        run: python batch.py
